# Volume mappings for lotus Docker image
# Format: host_subdirectory = "container_path"
# Host paths will be relative to ~/.foc-devnet/artifacts/docker/volumes/lotus/

[volumes]
# Lotus repository data
data = "/home/foc-user/.lotus-local-net"
# Genesis files
genesis = "/home/foc-user/.genesis"
