# Volume mappings for builder Docker image
# Format: host_subdirectory = "container_path"
# Host paths will be relative to ~/.foc-localnet/artifacts/docker/volumes/builder/

[volumes]
cargo = "/home/foc-user/.cargo"
rustup = "/home/foc-user/.rustup"
go = "/home/foc-user/go"
