# Volume mappings for curio Docker image
# Format: host_subdirectory = "container_path"
# Host paths will be relative to ~/.foc-localnet/artifacts/docker/volumes/curio/

[volumes]
# Curio repository data
data = "/root/.curio"
