//! Verification utilities for Lotus-Miner.
//!
//! This module provides utilities for verifying Lotus-Miner startup and functionality.

use std::error::Error;
use std::process::Command;
use std::thread;
use std::time::Duration;

use super::constants::{
    LOTUS_MINER_PORTS, MINER_API_CHECK_DELAY_SECS, PORT_WAIT_TIMEOUT_SECS, TIPSET_CHECK_DELAY_SECS,
};
use crate::commands::start::step::StepContext;
use crate::docker::containers::{lotus_container_name, lotus_miner_container_name};
use crate::docker::{container_is_running, wait_for_port};

/// Get the Lotus-Miner container name from context
fn get_container_name(context: &StepContext) -> Result<String, Box<dyn Error>> {
    let run_id = context.run_id().ok_or("Run ID not found in context")?;
    Ok(lotus_miner_container_name(run_id))
}

/// Get the Lotus container name from context
fn get_lotus_container_name(context: &StepContext) -> Result<String, Box<dyn Error>> {
    let run_id = context.run_id().ok_or("Run ID not found in context")?;
    Ok(lotus_container_name(run_id))
}

/// Check if lotus-miner is responsive
pub fn check_miner_api(context: &StepContext) -> Result<(), Box<dyn Error>> {
    let container_name = get_container_name(context)?;

    // Try to execute a simple lotus-miner command via docker exec
    let output = Command::new("docker")
        .args([
            "exec",
            &container_name,
            "/usr/local/bin/lotus-bins/lotus-miner",
            "version",
        ])
        .output()?;

    if !output.status.success() {
        return Err(format!(
            "Lotus-Miner API check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }

    Ok(())
}

/// Check if tipsets are being generated by waiting and comparing chain heights
pub fn check_tipset_generation(context: &StepContext) -> Result<(), Box<dyn Error>> {
    let lotus_name = get_lotus_container_name(context)?;

    // Get initial chain height
    let output1 = Command::new("docker")
        .args([
            "exec",
            &lotus_name,
            "/usr/local/bin/lotus-bins/lotus",
            "chain",
            "list",
            "--count=1",
        ])
        .output()?;

    if !output1.status.success() {
        return Err("Failed to get initial chain height".into());
    }

    let chain_output1 = String::from_utf8_lossy(&output1.stdout);
    let height1 = parse_chain_height(&chain_output1)?;

    println!(
        "      Waiting {} seconds to check for new blocks...",
        TIPSET_CHECK_DELAY_SECS
    );
    thread::sleep(Duration::from_secs(TIPSET_CHECK_DELAY_SECS));

    // Get new chain height
    let output2 = Command::new("docker")
        .args([
            "exec",
            &lotus_name,
            "/usr/local/bin/lotus-bins/lotus",
            "chain",
            "list",
            "--count=1",
        ])
        .output()?;

    if !output2.status.success() {
        return Err("Failed to get new chain height".into());
    }

    let chain_output2 = String::from_utf8_lossy(&output2.stdout);
    let height2 = parse_chain_height(&chain_output2)?;

    // Check if height increased
    if height2 > height1 {
        println!(
            "      Chain height increased from {} to {} - blocks are being produced!",
            height1, height2
        );
        Ok(())
    } else {
        Err(format!(
            "Chain height did not increase (was {} , still {}). Blocks may not be producing.",
            height1, height2
        )
        .into())
    }
}

/// Parse chain height from lotus chain list output
/// Expected format: "5: (Nov 26 12:05:25) [ bafy...: t01000, ]"
fn parse_chain_height(output: &str) -> Result<u64, Box<dyn Error>> {
    // Get first line and extract the number before the colon
    if let Some(first_line) = output.lines().next() {
        if let Some(colon_pos) = first_line.find(':') {
            let height_str = first_line[..colon_pos].trim();
            return height_str
                .parse::<u64>()
                .map_err(|e| format!("Failed to parse height '{}': {}", height_str, e).into());
        }
    }
    Err("Could not parse chain height from output".into())
}

/// Perform post-execution verification for Lotus-Miner startup
pub fn perform_post_execution_verification(context: &StepContext) -> Result<(), Box<dyn Error>> {
    use crossterm::style::Stylize;

    let container_name = get_container_name(context)?;
    let lotus_name = get_lotus_container_name(context)?;

    // Wait for container to initialize
    println!("    Waiting for Lotus-Miner to initialize (this may take a while)...");
    thread::sleep(Duration::from_secs(15)); // CONTAINER_INIT_WAIT_SECS

    // Verify container is running
    if !container_is_running(&container_name)? {
        // Check logs for errors
        let logs_output = Command::new("docker")
            .args(["logs", "--tail", "50", &container_name])
            .output()?;

        return Err(format!(
            "Container stopped unexpectedly. Logs:\n{}",
            String::from_utf8_lossy(&logs_output.stdout)
        )
        .into());
    }
    println!("    {} Container is running", "✓".green());

    // Check all ports are accessible
    println!("    Verifying port accessibility...");
    for &(port, description) in LOTUS_MINER_PORTS {
        print!("      Checking port {} ({})... ", port, description);
        match wait_for_port(port, PORT_WAIT_TIMEOUT_SECS) {
            Ok(_) => println!("{}", "✓".green()),
            Err(e) => {
                println!("{}", "⚠".yellow());
                println!(
                    "      Note: Port {} may not be immediately available: {}",
                    port, e
                );
            }
        }
    }

    // Verify Lotus-Miner API is responsive
    println!("    Verifying Lotus-Miner API connectivity...");
    thread::sleep(Duration::from_secs(MINER_API_CHECK_DELAY_SECS)); // Give miner time to fully initialize
    match check_miner_api(context) {
        Ok(_) => {
            println!(
                "    {} Lotus-Miner is ready and responding to API calls",
                "✓".green()
            );
        }
        Err(e) => {
            println!(
                "    {} Lotus-Miner API verification failed: {}",
                "⚠".yellow(),
                e
            );
            println!(
                "    Note: Lotus-Miner may still be initializing. This is usually not a critical error."
            );
        }
    }

    // Verify tipset generation (block production)
    println!("    Verifying tipset generation...");
    match check_tipset_generation(context) {
        Ok(_) => {
            println!(
                "    {} Tipsets are being generated (blocks are being produced)!",
                "✓".green().bold()
            );
        }
        Err(e) => {
            println!("    {} Tipset generation check failed: {}", "⚠".yellow(), e);
            println!("    Note: The miner may take a few moments to start producing blocks.");
        }
    }

    println!("\n    {} Lotus-Miner is ready!", "✓".green().bold());
    println!("      API endpoint: http://localhost:2345");
    println!(
        "\n    {} The local Filecoin network is now running and producing tipsets!",
        "🎉".bold()
    );
    println!(
        "      Check chain status: docker exec {} /usr/local/bin/lotus-bins/lotus chain list",
        lotus_name
    );

    Ok(())
}
